"use client";

import { Suspense, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ChevronLeft, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/page-header";
import { ReportHeaderBar } from "@/components/reports/report-header-bar";
import { ReportPreviewCard } from "@/components/reports/report-preview-card";
import { DownloadReportButtons } from "@/components/reports/download-report-buttons";
import { useReportPreview } from "@/components/reports/use-report-preview";
import { formatDisplayDate } from "@/lib/reports";

/**
 * Generate Preview navigates here instead of updating the filter page
 * in-place — a real page/URL for the report, not just inline state, per
 * explicit direction. Reads the filters the previous screen already
 * validated (passed as query params) purely for display; it doesn't
 * re-validate or refetch anything itself.
 */
export default function ReportPreviewPage() {
  return (
    <Suspense fallback={null}>
      <ReportPreviewContent />
    </Suspense>
  );
}

function ReportPreviewContent() {
  const router = useRouter();
  const params = useSearchParams();
  const { phase, reportId, generate } = useReportPreview();

  const type = params.get("type") === "kvk" ? "kvk" : "admin";
  const backHref = "/reports";

  /**
   * A Host Organisation scoped down to "All KVKs" is its own report kind —
   * an aggregate across every KVK under that one organisation — distinct
   * from the fully collective Super Admin report (no organisation picked)
   * and from a single-KVK report. Client direction: "organisation and host
   * wala bhi banega" — Reports needs this scope explicitly labeled, not
   * just folded into the generic Super Admin report.
   */
  const hostOrg = params.get("hostOrg") ?? "";
  const kvk = params.get("kvk") ?? "";
  const isOrgScoped = type === "admin" && hostOrg !== "" && hostOrg !== "All Host Organizations" && (kvk === "" || kvk === "All KVKs");

  const reportKind = type === "kvk" ? "kvk" : isOrgScoped ? "org" : "admin";
  const reportTitle =
    reportKind === "kvk" ? "KVK REPORT PREVIEW" : reportKind === "org" ? "HOST ORGANISATION REPORT PREVIEW" : "SUPER ADMIN REPORT PREVIEW";
  const reportHeading =
    reportKind === "kvk" ? "KVK REPORT PREVIEW" : reportKind === "org" ? "HOST ORGANISATION REPORT" : "REPORT SUMMARY";

  useEffect(() => {
    generate(() => null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const metaColumns =
    type === "kvk"
      ? [
          [
            { label: "KVK Name", value: params.get("kvk") ?? "" },
            { label: "Form", value: params.get("form") ?? "All Forms" },
          ],
          [
            { label: "From Date", value: formatDisplayDate(params.get("from") ?? "") },
            { label: "To Date", value: formatDisplayDate(params.get("to") ?? "") },
          ],
        ]
      : [
          [
            { label: "Zone", value: params.get("zone") ?? "" },
            { label: "State", value: params.get("state") ?? "" },
            { label: "Host Organisation", value: params.get("hostOrg") ?? "" },
          ],
          [
            { label: "KVK", value: params.get("kvk") ?? "" },
            { label: "Form", value: params.get("form") ?? "All Forms" },
          ],
          [
            { label: "From Date", value: formatDisplayDate(params.get("from") ?? "") },
            { label: "To Date", value: formatDisplayDate(params.get("to") ?? "") },
            { label: "Generated By", value: reportKind === "org" ? `${hostOrg} (Host Organisation)` : "Super Admin" },
          ],
        ];

  return (
    <div className="space-y-4">
      <PageHeader trail={[{ label: "Reports", href: "/reports" }, { label: "Report Preview" }]} />

      <ReportHeaderBar title={reportTitle} />

      <Button variant="outline" size="sm" onClick={() => router.push(backHref)}>
        <ChevronLeft className="size-3.5" />
        Back to Filters
      </Button>

      <div>
        <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold tracking-wide text-primary uppercase">
          <Eye className="size-3.5" />
          Report Preview
        </div>
        <ReportPreviewCard
          heading={reportHeading}
          reportId={reportId}
          phase={phase}
          metaColumns={metaColumns}
        />
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-card p-4">
        <div>
          <p className="mb-2 text-xs font-medium text-muted-foreground">Download Report</p>
          <DownloadReportButtons enabled={false} />
        </div>
      </div>
    </div>
  );
}
