"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ChevronLeft, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/page-header";
import { ReportHeaderBar } from "@/components/reports/report-header-bar";
import { ReportPreviewCard } from "@/components/reports/report-preview-card";
import { DownloadReportButtons } from "@/components/reports/download-report-buttons";
import { useReportPreview } from "@/components/reports/use-report-preview";
import { formatDisplayDate } from "@/lib/reports";
import type { ReportSection } from "@/lib/report-data";

/**
 * Generate Preview navigates here instead of updating the filter page
 * in-place - a real page/URL for the report, not just inline state, per
 * explicit direction. Reads the filters the previous screen already
 * validated (passed as query params) purely for display; it doesn't
 * re-validate or refetch anything itself.
 */
export default function ReportPreviewPage() {
  return (
    <Suspense fallback={null}>
      <ReportPreviewContent />
    </Suspense>
  );
}

function ReportPreviewContent() {
  const router = useRouter();
  const params = useSearchParams();
  const { phase, reportId, generate } = useReportPreview();

  const type = params.get("type") === "kvk" ? "kvk" : "admin";
  const backHref = "/reports";
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError, setPdfError] = useState<string | null>(null);

  useEffect(() => {
    generate(() => null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleDownloadPdf() {
    setPdfError(null);
    setPdfLoading(true);
    try {
      const kvkFilter = params.get("kvk");
      const query = kvkFilter ? `?kvk=${encodeURIComponent(kvkFilter)}` : "";
      const response = await fetch(`/api/reports/generate${query}`);
      const data: { zoneLabel: string; kvkNames: string[]; sections: ReportSection[] } | { error: string } =
        await response.json();
      if (!response.ok || "error" in data) {
        setPdfError("error" in data ? data.error : "Could not generate the report.");
        return;
      }
      const { generateReportPdf } = await import("@/lib/report-pdf");
      const doc = generateReportPdf({
        title: "ATARI AMS REPORT",
        zoneLabel: data.zoneLabel,
        reportingYearLabel: "All Data",
        kvkNames: data.kvkNames,
        sections: data.sections,
      });
      doc.save(`ATARI-AMS-Report-${new Date().toISOString().slice(0, 10)}.pdf`);
    } catch {
      setPdfError("Could not reach the server. Please try again.");
    } finally {
      setPdfLoading(false);
    }
  }

  const metaColumns =
    type === "kvk"
      ? [
          [
            { label: "KVK Name", value: params.get("kvk") ?? "" },
            { label: "Form", value: params.get("form") ?? "All Forms" },
          ],
          [
            {
              label: "From Date",
              value: formatDisplayDate(params.get("from") ?? ""),
            },
            {
              label: "To Date",
              value: formatDisplayDate(params.get("to") ?? ""),
            },
          ],
        ]
      : [
          [
            { label: "Zone", value: params.get("zone") ?? "" },
            { label: "State", value: params.get("state") ?? "" },
            { label: "Host Organisation", value: params.get("hostOrg") ?? "" },
            { label: "District", value: params.get("district") ?? "" },
          ],
          [
            { label: "KVK", value: params.get("kvk") ?? "" },
            { label: "Form", value: params.get("form") ?? "All Forms" },
          ],
          [
            {
              label: "From Date",
              value: formatDisplayDate(params.get("from") ?? ""),
            },
            {
              label: "To Date",
              value: formatDisplayDate(params.get("to") ?? ""),
            },
            { label: "Generated By", value: "Super Admin" },
          ],
        ];

  return (
    <div className="space-y-4">
      <PageHeader
        trail={[
          { label: "Reports", href: "/reports" },
          { label: "Report Preview" },
        ]}
      />

      <ReportHeaderBar
        title={
          type === "kvk" ? "KVK REPORT PREVIEW" : "SUPER ADMIN REPORT PREVIEW"
        }
      />

      <Button variant="outline" size="sm" onClick={() => router.push(backHref)}>
        <ChevronLeft className="size-3.5" />
        Back to Filters
      </Button>

      <div>
        <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold tracking-wide text-primary uppercase">
          <Eye className="size-3.5" />
          Report Preview
        </div>
        <ReportPreviewCard
          heading={type === "kvk" ? "KVK REPORT PREVIEW" : "REPORT SUMMARY"}
          reportId={reportId}
          phase={phase}
          metaColumns={metaColumns}
        />
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-card p-4">
        <div>
          <p className="mb-2 text-xs font-medium text-muted-foreground">
            Download Report
          </p>
          <DownloadReportButtons onDownloadPdf={handleDownloadPdf} pdfLoading={pdfLoading} />
          {pdfError && (
            <p role="alert" className="mt-2 text-sm font-medium text-destructive">
              {pdfError}
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
