-- AlterTable
ALTER TABLE "NariBioFortified" ADD COLUMN     "areaHa" DECIMAL(10,2),
ADD COLUMN     "consumptionDetails" JSONB,
ADD COLUMN     "cropName" TEXT,
ADD COLUMN     "obcFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "obcMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "variety" TEXT;

-- AlterTable
ALTER TABLE "NariExtension" ADD COLUMN     "obcFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "obcMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stMale" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "NariNutritionGarden" ADD COLUMN     "crops" JSONB,
ADD COLUMN     "obcFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "obcMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stMale" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "NariTraining" ADD COLUMN     "obcFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "obcMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "onOffCampus" TEXT,
ADD COLUMN     "scFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "venue" TEXT;

-- AlterTable
ALTER TABLE "NariValueAddition" ADD COLUMN     "obcFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "obcMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "products" JSONB,
ADD COLUMN     "scFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scMale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stFemale" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stMale" INTEGER NOT NULL DEFAULT 0;
