-- Real "Farmers Details" block confirmed on the client's own Add OFT form (AMS_User_Manual.pdf p.14): General_M/F, OBC_M/F, SC_M/F, ST_M/F.
ALTER TABLE "Oft" ADD COLUMN "generalMale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "generalFemale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "obcMale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "obcFemale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "scMale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "scFemale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "stMale" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Oft" ADD COLUMN "stFemale" INTEGER NOT NULL DEFAULT 0;
